### ISSUE TITLE
Upgrade ngx-translate/core and angular peerDependencies

### ISSUE THREAD

**Issue by aalmazanarbs** [mwootendev/ngx-translate-plugins#1]
After upgrade to Angular 7 and ngx-translate/core 11 the following error is displaying when using the last version of the package:
`npm WARN ngx-translate-testing@1.0.0 requires a peer of @angular/common@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-translate-testing@1.0.0 requires a peer of @angular/core@^6.0.0-rc.0 || ^6.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN ngx-translate-testing@1.0.0 requires a peer of @ngx-translate/core@^10.0.0 but none is installed. You must install peer dependencies yourself.`

I think peerDependencies must be update to:
`"@angular/common": "^7.0.0-rc.0 || ^7.0.0",
"@angular/core": "^7.0.0-rc.0 || ^7.0.0",
"@ngx-translate/core": "^11.0.0",`

**Comment by mwootendev** [comment]
I just pushed a new version 2.0.0 which should support Angular 7.
