### ISSUE TITLE
Add Angular 12 support

### ISSUE THREAD

**Issue by benbold** [mwootendev/ngx-translate-plugins#32]
**Describe the bug**
Getting the following warnings while migrating from Angular v11 => v12.

`Package "ngx-translate-testing" has an incompatible peer dependency to "@angular/common" (requires "^10.0.0-rc.0 || >=10.0.0 <11.0.0" (extended), would install "12.0.1").`
`Package "ngx-translate-testing" has an incompatible peer dependency to "@angular/core" (requires "^10.0.0-rc.0 || >=10.0.0 <11.0.0" (extended), would install "12.0.1").`

**Comment by drcarmen** [comment]
Same here ...

**Comment by drcarmen** [comment]
Anything new on this matter ?

**Comment by maxnag** [comment]
I also vote!

**Comment by mwootendev** [comment]
Sorry for the long delay. 5.2.0 should now be released. Special thanks to @atierant for the patch.
