### ISSUE TITLE
Angular 13 Support

### ISSUE THREAD

**Issue by SymbioticKilla** [mwootendev/ngx-translate-plugins#42]
Hi,

is there any plans to add support for Angular 13?

Thanks!

**Comment by sjarmero** [comment]
I've created PR #43, if anyone could test it and see if it works... I've run the tests locally and they passed, but it's better to be sure

**Comment by mwootendev** [comment]
My apologies, I've been in the process of changing jobs. Thank you @sjarmero for the pull request and I'll try to update the library this weekend.

**Comment by mwootendev** [comment]
I just pushed version 6.0.0 up to NPM. Thanks again @sjarmero for the patch.
