### ISSUE TITLE
6.0.0 : Class constructor TranslateLoader cannot be invoked without 'new'

### ISSUE THREAD

**Issue by wmarques** [mwootendev/ngx-translate-plugins#48]
**Describe the bug**
After upgrading to 6.0.0 and Angular 13 I'm having this error when running my test.

**To Reproduce**
Setup a project with latest version of Angular, NGX Translate and ngx-tranlate-testing

**Expected behavior**
It shouldn't output error

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS: Mac
 - Node 14

Thanks ! Tell me if I can help on resolving this bug

**Comment by wmarques** [comment]
Nevermind my Jest config was wrong, sorry !
EDIT: sorry I was wrong, even with a very basic Jest config I have the issue...

**Comment by mwootendev** [comment]
@wmarques I have not been able to reproduce this. Can you provide any additional details about your setup and how it differs from: https://github.com/mwootendev/ngx-translate-plugins/blob/develop/src/app/app.component.spec.ts#L22?

**Comment by vgunda** [comment]
@wmarques would you mind describing your problem and fix, as I currently have the same problem.

**Comment by JamesHenry** [comment]
@mwootendev You are not using jest in the example setup is the big difference I think - I have provided a write up in #50 as to an easy way to reproduce this and #49

**Comment by mwootendev** [comment]
@JamesHenry thanks for the explanation in #50. I was able to publish a new 6.0.1 version with Ivy partial support enabled. This should hopefully resolve this issue.
