### ISSUE TITLE
6.0.0: Unexpected value 'TranslateTestingModule' imported by the module 'DynamicTestModule'. Please add an @NgModule annotation.

### ISSUE THREAD

**Issue by joseluissb** [mwootendev/ngx-translate-plugins#49]
Describe the bug
After upgrading to 6.0.0 and Angular 13 I'm having this error when running my tests.

To Reproduce
- Setup a project with angular 13, ngx-translate 14 and ngx-tranlate-testing 6.0.0
- Create a test for a component with:
```
TestBed.configureTestingModule({
      providers: [MyComponent],
      imports: [
        TranslateTestingModule.withTranslations({
          en: require('src/assets/i18n/en-EN.json'),
        }),
      ],
      declarations: [MyComponent],
    }).compileComponents();
```

Expected behavior
- It shouldn't output error

Screenshots
- N/A

Desktop (please complete the following information):
- OS: Mac
- Node 14

**Comment by mwootendev** [comment]
@joseluissb Can you provide a little more detail about the error you are seeing? I have not been able to reproduce this issue with Angular 13.0.1 and ngx-translate 14.0.0 on Node 14.17.1. Can you explain how your setup is different than the one I'm using here: https://github.com/mwootendev/ngx-translate-plugins/blob/develop/src/app/app.component.spec.ts#L22?

**Comment by JamesHenry** [comment]
@mwootendev As per my other note I have provided a write up in #50 which reproduces this, the key point is that jest is the test runner

**Comment by joseluissb** [comment]
@mwootendev thanks for the help. The only difference I can see is that we use Jest and it started happening after we migrated to Angular 13.

Also, we don't use the `.withCompiler(new TranslateMessageFormatCompiler())` part, but I don't think that should be the problem.

Thanks

**Comment by mwootendev** [comment]
@JamesHenry thanks for the explanation in #50. I was able to publish a new 6.0.1 version with Ivy partial support enabled. This should hopefully resolve this issue.

**Comment by jeserkin** [comment]
Just today I installed all relevant versions of `@ngx-translate` and `ngx-translate-testing`, but I get same error in console.

```
const EMPTY_TRANSLATIONS = { ['et']: {}, ['en']: {} };

  beforeEach(waitForAsync(() => {
    TestBed.configureTestingModule({
      declarations: [
        ContactGroupCardComponent
      ],
      imports: [
        RouterTestingModule,
        TranslateTestingModule.withTranslations(EMPTY_TRANSLATIONS)
      ]
    })
      .compileComponents();
  }));
```

was there a solution here and I missed it or is it still an existing issue?

Thank you.
