### ISSUE TITLE
Using require() instead of import

### ISSUE THREAD

**Issue by azollai** [mwootendev/ngx-translate-plugins#5]
Is there a specific reason why you are using require() and not import?
E.g. `import * as translation from '../../i18n/hu.json';`
```
TranslateTestingModule.withTranslations(ENGLISH_LANGUAGE, ENGLISH_TRANSLATIONS)
  .withTranslations(SPANISH_LANGUAGE, SPANISH_TRANSLATIONS)
  .withTranslations(ENGLISH_LANGUAGE, require('../../assets/i18n/en.json'))
```

**Comment by mwootendev** [comment]
The original version was written against Angular 6 with TypeScript 2.7, which at the time did not support that feature.
